image_size: [1280, 736]
ball_target_position: [0.5, 0.7]
frequence: 100
max_yaw: [-1, 1]  # clamp to [min, max]
max_pitch: [0.2, 0.785]  # clamp [min, max]
converge_to_ball_P: [0.3, 0.3]
converge_to_ball_D: [0.05, 0.05]
input_filter_alpha: 0.5  # exp-filter args, higher is smoother
confidence_threshold: 0.6
EWMA_ball_confidence_factor: 0.9
EWMA_ball_confidence_threshold: 0.5
interpolation: true
look_for_ball_point:  # pitch, yaw, duration
  - [[-0.7, 0.0], 1.0]
  - [[ 0.7, 0.0], 1.5]
  - [[ 0.7, 1.0], 1.0]
  - [[-0.7, 1.0], 1.5]
